set_property -dict { PACKAGE_PIN A5    IOSTANDARD LVCMOS33 } [get_ports { A[0] }]; 
set_property -dict { PACKAGE_PIN B6    IOSTANDARD LVCMOS33 } [get_ports { A[1] }]; 
set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { A[2] }]; 
set_property -dict { PACKAGE_PIN C3    IOSTANDARD LVCMOS33 } [get_ports { A[3] }]; 
set_property -dict { PACKAGE_PIN C4    IOSTANDARD LVCMOS33 } [get_ports { B[0] }]; 
set_property -dict { PACKAGE_PIN A10   IOSTANDARD LVCMOS33 } [get_ports { B[1] }]; 
set_property -dict { PACKAGE_PIN B13   IOSTANDARD LVCMOS33 } [get_ports { B[2] }]; 
set_property -dict { PACKAGE_PIN C14   IOSTANDARD LVCMOS33 } [get_ports { B[3] }]; 
set_property -dict { PACKAGE_PIN D13   IOSTANDARD LVCMOS33 } [get_ports { SEL[0] }]; 
set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { SEL[1] }]; 
set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { SEL[2] }]; 
set_property -dict { PACKAGE_PIN H13   IOSTANDARD LVCMOS33 } [get_ports { SEL[3] }]; 
set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33} [get_ports {Y[0]}]; 
set_property -dict { PACKAGE_PIN E4    IOSTANDARD LVCMOS33} [get_ports {Y[1]}]; 
set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33} [get_ports {Y[2]}]; 
set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33} [get_ports {Y[3]}];